kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID:-utbetaling}
  brokers: ${KAFKA_BROKERS:-localhost:9092}
  security: ${KAFKA_SECURITY_ENABLED:-false}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH:-}
  keystorePath: ${KAFKA_KEYSTORE_PATH:-}
  credstorePsw: ${KAFKA_CREDSTORE_PASSWORD:-}
  clientId: ${KAFKA_CLIENT_ID:-utbetaling}
