@startuml
!theme black-knight
queue "aap.mottakere.v1" <<topic>> as aap_mottakere_v1
queue "aap.vedtak.v1" <<topic>> as aap_vedtak_v1
package "Sub-topology: 0" {
	database "mottakere-state-store" <<State Store>> as mottakere_state_store
	agent "consume-aap.vedtak.v1" <<Source>> as consume_aap_vedtak_v1
	agent "KSTREAM-PEEK-0000000006" <<Processor>> as KSTREAM_PEEK_0000000006
	agent "consume-aap.mottakere.v1" <<Source>> as consume_aap_mottakere_v1
	agent "filter-vedtak-tombstone" <<Processor>> as filter_vedtak_tombstone
	agent "KSTREAM-PEEK-0000000001" <<Processor>> as KSTREAM_PEEK_0000000001
	agent "aap.vedtak.v1-joined-aap.mottakere.v1" <<Processor>> as aap_vedtak_v1_joined_aap_mottakere_v1
	agent "KSTREAM-MAPVALUES-0000000009" <<Processor>> as KSTREAM_MAPVALUES_0000000009
	agent "filter-mottakere-tombstone" <<Processor>> as filter_mottakere_tombstone
	agent "KSTREAM-PEEK-0000000003" <<Processor>> as KSTREAM_PEEK_0000000003
	agent "KSTREAM-PEEK-0000000010" <<Processor>> as KSTREAM_PEEK_0000000010
	agent "mottakere-as-table" <<Processor>> as mottakere_as_table
	agent "produced-mottakere" <<Sink>> as produced_mottakere
	aap_vedtak_v1 --> consume_aap_vedtak_v1
	aap_mottakere_v1 --> consume_aap_mottakere_v1
	mottakere_state_store -- aap_vedtak_v1_joined_aap_mottakere_v1
	mottakere_state_store -- mottakere_as_table
	aap_mottakere_v1 <-- produced_mottakere
	consume_aap_vedtak_v1 --> KSTREAM_PEEK_0000000006
	KSTREAM_PEEK_0000000006 --> filter_vedtak_tombstone
	consume_aap_mottakere_v1 --> KSTREAM_PEEK_0000000001
	filter_vedtak_tombstone --> aap_vedtak_v1_joined_aap_mottakere_v1
	KSTREAM_PEEK_0000000001 --> filter_mottakere_tombstone
	aap_vedtak_v1_joined_aap_mottakere_v1 --> KSTREAM_MAPVALUES_0000000009
	KSTREAM_MAPVALUES_0000000009 --> KSTREAM_PEEK_0000000010
	filter_mottakere_tombstone --> KSTREAM_PEEK_0000000003
	KSTREAM_PEEK_0000000003 --> mottakere_as_table
	KSTREAM_PEEK_0000000010 --> produced_mottakere
}
@enduml