@startuml
!theme black-knight
queue "aap.mottakere.v1" <<topic>> as aap_mottakere_v1
queue "aap.meldeplikt.v1" <<topic>> as aap_meldeplikt_v1
queue "aap.utbetalingsbehov.v1" <<topic>> as aap_utbetalingsbehov_v1
queue "aap.vedtak.v1" <<topic>> as aap_vedtak_v1
package "Sub-topology: 0" {
	database "mottakere-state-store" <<State Store>> as mottakere_state_store
	agent "consume-aap.meldeplikt.v1" <<Source>> as consume_aap_meldeplikt_v1
	agent "consume-aap.utbetalingsbehov.v1" <<Source>> as consume_aap_utbetalingsbehov_v1
	agent "consume-aap.vedtak.v1" <<Source>> as consume_aap_vedtak_v1
	agent "KSTREAM-PEEK-0000000006" <<Processor>> as KSTREAM_PEEK_0000000006
	agent "KSTREAM-PEEK-0000000013" <<Processor>> as KSTREAM_PEEK_0000000013
	agent "KSTREAM-PEEK-0000000020" <<Processor>> as KSTREAM_PEEK_0000000020
	agent "consume-aap.mottakere.v1" <<Source>> as consume_aap_mottakere_v1
	agent "filter-losning-tombstone" <<Processor>> as filter_losning_tombstone
	agent "filter-meldepliktshendelse-tombstone" <<Processor>> as filter_meldepliktshendelse_tombstone
	agent "filter-vedtakshendelse-tombstone" <<Processor>> as filter_vedtakshendelse_tombstone
	agent "KSTREAM-PEEK-0000000001" <<Processor>> as KSTREAM_PEEK_0000000001
	agent "aap.meldeplikt.v1-joined-aap.mottakere.v1" <<Processor>> as aap_meldeplikt_v1_joined_aap_mottakere_v1
	agent "aap.utbetalingsbehov.v1-joined-aap.mottakere.v1" <<Processor>> as aap_utbetalingsbehov_v1_joined_aap_mottakere_v1
	agent "aap.vedtak.v1-joined-aap.mottakere.v1" <<Processor>> as aap_vedtak_v1_joined_aap_mottakere_v1
	agent "KSTREAM-MAPVALUES-0000000009" <<Processor>> as KSTREAM_MAPVALUES_0000000009
	agent "KSTREAM-MAPVALUES-0000000016" <<Processor>> as KSTREAM_MAPVALUES_0000000016
	agent "KSTREAM-MAPVALUES-0000000023" <<Processor>> as KSTREAM_MAPVALUES_0000000023
	agent "filter-mottakere-tombstone" <<Processor>> as filter_mottakere_tombstone
	agent "KSTREAM-PEEK-0000000003" <<Processor>> as KSTREAM_PEEK_0000000003
	agent "KSTREAM-PEEK-0000000010" <<Processor>> as KSTREAM_PEEK_0000000010
	agent "KSTREAM-PEEK-0000000017" <<Processor>> as KSTREAM_PEEK_0000000017
	agent "KSTREAM-PEEK-0000000024" <<Processor>> as KSTREAM_PEEK_0000000024
	agent "mottakere-as-table" <<Processor>> as mottakere_as_table
	agent "produced-mottakere-for-losning" <<Sink>> as produced_mottakere_for_losning
	agent "produced-mottakere-for-meldeplikt" <<Sink>> as produced_mottakere_for_meldeplikt
	agent "produced-mottakere-for-vedtak" <<Sink>> as produced_mottakere_for_vedtak
	aap_meldeplikt_v1 --> consume_aap_meldeplikt_v1
	aap_utbetalingsbehov_v1 --> consume_aap_utbetalingsbehov_v1
	aap_vedtak_v1 --> consume_aap_vedtak_v1
	aap_mottakere_v1 --> consume_aap_mottakere_v1
	mottakere_state_store -- aap_meldeplikt_v1_joined_aap_mottakere_v1
	mottakere_state_store -- aap_utbetalingsbehov_v1_joined_aap_mottakere_v1
	mottakere_state_store -- aap_vedtak_v1_joined_aap_mottakere_v1
	mottakere_state_store -- mottakere_as_table
	aap_mottakere_v1 <-- produced_mottakere_for_losning
	aap_mottakere_v1 <-- produced_mottakere_for_meldeplikt
	aap_mottakere_v1 <-- produced_mottakere_for_vedtak
	consume_aap_meldeplikt_v1 --> KSTREAM_PEEK_0000000013
	consume_aap_utbetalingsbehov_v1 --> KSTREAM_PEEK_0000000020
	consume_aap_vedtak_v1 --> KSTREAM_PEEK_0000000006
	KSTREAM_PEEK_0000000006 --> filter_vedtakshendelse_tombstone
	KSTREAM_PEEK_0000000013 --> filter_meldepliktshendelse_tombstone
	KSTREAM_PEEK_0000000020 --> filter_losning_tombstone
	consume_aap_mottakere_v1 --> KSTREAM_PEEK_0000000001
	filter_losning_tombstone --> aap_utbetalingsbehov_v1_joined_aap_mottakere_v1
	filter_meldepliktshendelse_tombstone --> aap_meldeplikt_v1_joined_aap_mottakere_v1
	filter_vedtakshendelse_tombstone --> aap_vedtak_v1_joined_aap_mottakere_v1
	KSTREAM_PEEK_0000000001 --> filter_mottakere_tombstone
	aap_meldeplikt_v1_joined_aap_mottakere_v1 --> KSTREAM_MAPVALUES_0000000016
	aap_utbetalingsbehov_v1_joined_aap_mottakere_v1 --> KSTREAM_MAPVALUES_0000000023
	aap_vedtak_v1_joined_aap_mottakere_v1 --> KSTREAM_MAPVALUES_0000000009
	KSTREAM_MAPVALUES_0000000009 --> KSTREAM_PEEK_0000000010
	KSTREAM_MAPVALUES_0000000016 --> KSTREAM_PEEK_0000000017
	KSTREAM_MAPVALUES_0000000023 --> KSTREAM_PEEK_0000000024
	filter_mottakere_tombstone --> KSTREAM_PEEK_0000000003
	KSTREAM_PEEK_0000000003 --> mottakere_as_table
	KSTREAM_PEEK_0000000010 --> produced_mottakere_for_vedtak
	KSTREAM_PEEK_0000000017 --> produced_mottakere_for_meldeplikt
	KSTREAM_PEEK_0000000024 --> produced_mottakere_for_losning
}
@enduml