name: Deploy Topics

on:
  push:
    branches:
      - main
    paths:
      - '.nais/topic-*.yml'
      - '.github/workflows/deploy-topics.yml'
      - '.nais/dev.yml'
      - '.nais/prod.yml'

jobs:
  deploy:
    strategy:
      matrix:
        name:
          - topic-utbetalingsbehov.yml
          - topic-mottakere.yml
        cluster:
          - dev-gcp
          - prod-gcp
        include:
          - cluster: dev-gcp
            vars: dev.yml
          - cluster: prod-gcp
            vars: prod.yml
    name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/${{ matrix.name }}
          VARS: .nais/${{ matrix.vars }}
          PRINT_PAYLOAD: true
